version: '3.7'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/myfolder/src
      - ./.env:/myfolder/.env

  my_database:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'boss_raid'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports:
      - 3307:3306

  my_redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
